use crate::{
    ideal::{Ideal, IdealCheck},
    ideal_collector::IdealOrZero,
};
use crypto_primitives::{FromWithConfig, PrimeField, Semiring};
use num_traits::Zero;
use zinc_poly::{EvaluatablePolynomial, univariate::dynamic::over_field::DynamicPolynomialF};
use zinc_utils::from_ref::FromRef;

/// An ideal of `R[X]` generated by a polynomial of the form
/// `X - generating_root`. Note the sign.
/// To have an ideal of the form `X + generating_root`
/// pass `-generating_root` when constructing.
#[derive(Clone, Copy, Debug)]
pub struct DegreeOneIdeal<R: Semiring> {
    generating_root: R,
}

impl<R: Semiring> DegreeOneIdeal<R> {
    /// Creates a new ideal of `R[X]` generated by `X - generating_root`.
    pub fn new(generating_root: R) -> Self {
        Self { generating_root }
    }
}

impl<R: Semiring> FromRef<DegreeOneIdeal<R>> for DegreeOneIdeal<R> {
    #[inline(always)]
    fn from_ref(ideal: &DegreeOneIdeal<R>) -> Self {
        ideal.clone()
    }
}

impl<R: Semiring> Ideal for DegreeOneIdeal<R> {}

impl<F: PrimeField> DegreeOneIdeal<F> {
    pub fn from_with_cfg<R>(ideal_over_ring: &DegreeOneIdeal<R>, field_cfg: &F::Config) -> Self
    where
        R: Semiring,
        F: for<'a> FromWithConfig<&'a R>,
    {
        Self {
            generating_root: F::from_with_cfg(&ideal_over_ring.generating_root, field_cfg),
        }
    }
}

impl<F: PrimeField> IdealCheck<DynamicPolynomialF<F>> for IdealOrZero<DegreeOneIdeal<F>> {
    fn contains(&self, value: &DynamicPolynomialF<F>) -> bool {
        if value.is_zero() {
            return true;
        }

        match &self.ideal_or_zero {
            Some(DegreeOneIdeal { generating_root }) => {
                let field_cfg = value.coeffs[0].cfg();
                let root_in_field = F::from_with_cfg(generating_root.clone(), field_cfg);
                F::is_zero(
                    &value
                        .evaluate_at_point(&root_in_field)
                        .expect("arithmetic overflow"),
                )
            }
            None => value.is_zero(),
        }
    }
}
