use crate::{
    ideal::{Ideal, IdealCheck, IdealCheckError},
    ideal_collector::IdealOrZero,
};
use crypto_primitives::{FieldConfig, ProjectElementWithConfig, SemiringConfig, SetElement};
use num_traits::Euclid;
use std::fmt::{Display, Formatter};
use zinc_poly::univariate::dynamic::{DynamicPolynomial, DynamicPolynomialConfig};
use zinc_utils::from_ref::FromRef;

/// An ideal of `R[X]` generated by `X^W - generating_root`.
///
/// - `W = 1`: the ideal `(X - a)`, checked via point evaluation at `a`.
/// - `W > 1`: the ideal `(X^W - a)`, checked via polynomial reduction modulo
///   `X^W - a`.
///
/// The compile-time `W` parameter allows the membership check to
/// specialize: `W = 1` avoids allocating a remainder buffer and uses
/// Horner evaluation, while `W > 1` uses a chunk-based reduction.
#[derive(Clone, Copy, Debug)]
pub struct RotationIdeal<E: SetElement, const W: usize> {
    generating_root: E,
}

impl<E: SetElement, const W: usize> RotationIdeal<E, W> {
    /// Creates a new ideal of `R[X]` generated by `X^W - generating_root`.
    pub fn new(generating_root: E) -> Self {
        const { assert!(W >= 1, "Rotation ideal degree W must be at least 1") };
        Self { generating_root }
    }
}

impl<E: SetElement, const W: usize> FromRef<RotationIdeal<E, W>> for RotationIdeal<E, W> {
    #[inline(always)]
    fn from_ref(ideal: &RotationIdeal<E, W>) -> Self {
        ideal.clone()
    }
}

impl<E: SetElement, const W: usize> Ideal for RotationIdeal<E, W> {}

impl<E: SetElement, const W: usize> Display for RotationIdeal<E, W> {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        write!(f, "RotationIdeal<{:?}, {W}>", self.generating_root)
    }
}

impl<E: SetElement, const W: usize> RotationIdeal<E, W> {
    /// Project a rotation ideal over the ring `R` into the field configured
    /// by `field_cfg`, by projecting the generating root.
    pub fn project<C, R>(field_cfg: &C, ideal_over_ring: &RotationIdeal<R, W>) -> Self
    where
        C: FieldConfig + ProjectElementWithConfig<R> + SemiringConfig<Element = E>,
        R: SetElement,
    {
        Self {
            generating_root: field_cfg.project(&ideal_over_ring.generating_root),
        }
    }
}

impl<'a, C: FieldConfig, const W: usize> IdealCheck<DynamicPolynomialConfig<'a, C>>
    for IdealOrZero<RotationIdeal<C::Element, W>>
{
    fn contains(
        &self,
        cfg: &DynamicPolynomialConfig<'a, C>,
        value: &DynamicPolynomial<C::Element>,
    ) -> Result<bool, IdealCheckError> {
        if cfg.is_zero(value) {
            return Ok(true);
        }

        match self {
            IdealOrZero::NonZero(RotationIdeal { generating_root }) => {
                // Elements no longer carry a field config, so a modulus
                // mismatch between coefficients and the generating root is
                // not observable here: `cfg` is the single source of truth
                // for the field both live in.
                if W == 1 {
                    Ok(cfg.cfg.is_zero(
                        &cfg.evaluate_at_point(value, generating_root)
                            .expect("evaluation of a non-empty polynomial cannot fail"),
                    ))
                } else {
                    Ok(remainder_is_zero::<C, W>(
                        cfg.cfg,
                        &value.coeffs,
                        generating_root,
                    ))
                }
            }
            IdealOrZero::Zero => Ok(cfg.is_zero(value)),
        }
    }
}

/// Checks whether the polynomial with the given `coeffs` lies in the ideal
/// `(X^W - a)`, i.e., whether `p(X) mod (X^W - a) == 0`.
///
/// Groups coefficients into chunks of `W` and folds from highest to lowest
/// using `rem = a * rem + chunk`, which is the Horner scheme applied to the
/// "base-`X^W`" representation of `p(X)`.
#[allow(clippy::arithmetic_side_effects)] // Was hand-checked to be correct.
fn remainder_is_zero<C: SemiringConfig, const W: usize>(
    cfg: &C,
    coeffs: &[C::Element],
    a: &C::Element,
) -> bool {
    debug_assert!(W > 0, "Was pre-checked so this cannot fail");

    if coeffs.is_empty() {
        return true;
    }

    let mut rem: [C::Element; W] = std::array::from_fn(|_| cfg.zero());

    let n = coeffs.len();
    let (num_full_chunks, partial_len) = n.div_rem_euclid(&W);

    if partial_len > 0 {
        let start = num_full_chunks * W;
        for (j, coeff) in coeffs[start..].iter().enumerate().take(partial_len) {
            rem[j] = coeff.clone();
        }
    }

    for chunk_idx in (0..num_full_chunks).rev() {
        let start = chunk_idx * W;
        for j in 0..W {
            cfg.mul_assign(&mut rem[j], a);
            cfg.add_assign(&mut rem[j], &coeffs[start + j]);
        }
    }

    rem.iter().all(|r| cfg.is_zero(r))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crypto_bigint::{U128, const_monty_params};
    use crypto_primitives::{FixedConfig, crypto_bigint_const_monty::ConstMontyField};
    use zinc_poly::univariate::dynamic::HasDynamicPolynomialConfig;

    const_monty_params!(Params, U128, "00000000b933426489189cb5b47d567f");
    type F = ConstMontyField<Params, { U128::LIMBS }>;
    type Cfg = FixedConfig<F>;

    fn poly(coeffs: &[i32]) -> DynamicPolynomial<F> {
        DynamicPolynomial::new(coeffs.iter().map(|&c| c.into()).collect::<Vec<_>>())
    }

    #[test]
    fn w1_ideal_contains_member() {
        // (X - 2): polynomial X - 2 should be in ideal (X-2) since eval at 2 is 0.
        let field_cfg = Cfg::default();
        let ideal = IdealOrZero::NonZero(RotationIdeal::<F, 1>::new(F::from(2)));
        let p = poly(&[-2, 1]); // X - 2
        assert!(ideal.contains(&field_cfg.dyn_poly_cfg(), &p).unwrap());
    }

    #[test]
    fn w1_ideal_rejects_nonmember() {
        let field_cfg = Cfg::default();
        let ideal = IdealOrZero::NonZero(RotationIdeal::<F, 1>::new(F::from(2)));
        let p = poly(&[1, 1]); // X + 1, eval at 2 = 3 ≠ 0
        assert!(!ideal.contains(&field_cfg.dyn_poly_cfg(), &p).unwrap());
    }

    #[test]
    fn w2_ideal_contains_generator() {
        // (X^2 - 1): the polynomial X^2 - 1 should be in this ideal.
        let field_cfg = Cfg::default();
        let ideal = IdealOrZero::NonZero(RotationIdeal::<F, 2>::new(F::from(1)));
        let p = poly(&[-1, 0, 1]); // X^2 - 1
        assert!(ideal.contains(&field_cfg.dyn_poly_cfg(), &p).unwrap());
    }

    #[test]
    fn w2_ideal_contains_multiple_of_generator() {
        // (X^2 - 1): X * (X^2 - 1) = X^3 - X should be in the ideal.
        let field_cfg = Cfg::default();
        let ideal = IdealOrZero::NonZero(RotationIdeal::<F, 2>::new(F::from(1)));
        let p = poly(&[0, -1, 0, 1]); // X^3 - X
        assert!(ideal.contains(&field_cfg.dyn_poly_cfg(), &p).unwrap());
    }

    #[test]
    fn w2_ideal_rejects_nonmember() {
        let field_cfg = Cfg::default();
        let ideal = IdealOrZero::NonZero(RotationIdeal::<F, 2>::new(F::from(1)));
        let p = poly(&[1, 1]); // X + 1
        assert!(!ideal.contains(&field_cfg.dyn_poly_cfg(), &p).unwrap());
    }

    #[test]
    fn w3_ideal_contains_member() {
        // (X^3 - 2): the polynomial X^3 - 2 should be in the ideal.
        let field_cfg = Cfg::default();
        let ideal = IdealOrZero::NonZero(RotationIdeal::<F, 3>::new(F::from(2)));
        let p = poly(&[-2, 0, 0, 1]); // X^3 - 2
        assert!(ideal.contains(&field_cfg.dyn_poly_cfg(), &p).unwrap());
    }

    #[test]
    fn w3_ideal_rejects_nonmember() {
        let field_cfg = Cfg::default();
        let ideal = IdealOrZero::NonZero(RotationIdeal::<F, 3>::new(F::from(2)));
        let p = poly(&[1, 0, 0, 1]); // X^3 + 1 (not in (X^3 - 2))
        assert!(!ideal.contains(&field_cfg.dyn_poly_cfg(), &p).unwrap());
    }

    #[test]
    fn zero_polynomial_always_in_ideal() {
        let field_cfg = Cfg::default();
        let ideal = IdealOrZero::NonZero(RotationIdeal::<F, 4>::new(F::from(5)));
        assert!(
            ideal
                .contains(&field_cfg.dyn_poly_cfg(), &DynamicPolynomial::<F>::ZERO)
                .unwrap()
        );
    }

    #[test]
    fn zero_ideal_only_contains_zero() {
        let field_cfg = Cfg::default();
        let zero_ideal = IdealOrZero::<RotationIdeal<F, 2>>::zero();
        assert!(
            zero_ideal
                .contains(&field_cfg.dyn_poly_cfg(), &DynamicPolynomial::<F>::ZERO)
                .unwrap()
        );
        assert!(
            !zero_ideal
                .contains(&field_cfg.dyn_poly_cfg(), &poly(&[1]))
                .unwrap()
        );
    }

    #[test]
    fn w2_reduction_cross_check_with_naive_substitution() {
        // Verify our specialized chunked-Horner reduction against an
        // independent naive algorithm: substitute $X^2 \to a$ one degree at
        // a time, folding the leading coefficient down until the degree
        // drops below 2.
        let field_cfg = Cfg::default();
        let cfg = field_cfg.dyn_poly_cfg();
        let a = F::from(3);
        let ideal = IdealOrZero::NonZero(RotationIdeal::<F, 2>::new(a));

        let is_member_naive = |p: &DynamicPolynomial<F>| {
            let mut coeffs = p.coeffs.clone();
            while coeffs.len() > 2 {
                let top = coeffs.pop().expect("len > 2");
                let idx = coeffs.len() - 2;
                let folded = field_cfg.mul(&top, &a);
                field_cfg.add_assign(&mut coeffs[idx], &folded);
            }
            coeffs.iter().all(|c| field_cfg.is_zero(c))
        };

        for p in [
            poly(&[1, 2, 3, 4, 5]),
            poly(&[0, 0, 0, 0, 6]),
            poly(&[-3, 0, 1]),        // X^2 - 3 itself
            poly(&[0, -3, 0, 1]),     // X * (X^2 - 3)
            poly(&[-9, 0, 6, 0, -1]), // -(X^2 - 3)^2
            poly(&[-8, 0, 6, 0, -1]), // -(X^2 - 3)^2 + 1
        ] {
            assert_eq!(
                ideal.contains(&cfg, &p).unwrap(),
                is_member_naive(&p),
                "Mismatch for polynomial: {p}"
            );
        }
    }
}
