#![allow(clippy::arithmetic_side_effects)] // Field arithmetic has no side effects.

use crate::{
    ideal::{Ideal, IdealCheck},
    ideal_collector::IdealOrZero,
};
use crypto_primitives::PrimeField;
use num_traits::Zero;
use zinc_poly::univariate::dynamic::over_field::DynamicPolynomialF;
use zinc_utils::from_ref::FromRef;

/// The ideal of `R[X]` generated by `X^N - 1`.
/// `N` is a const generic; the ideal carries no runtime data.
#[derive(Clone, Copy, Debug, Default)]
pub struct XnMinusOneIdeal<const N: usize>;

impl<const N: usize> XnMinusOneIdeal<N> {
    pub const fn new() -> Self {
        Self
    }
}

impl<const N: usize> FromRef<XnMinusOneIdeal<N>> for XnMinusOneIdeal<N> {
    #[inline(always)]
    fn from_ref(_ideal: &XnMinusOneIdeal<N>) -> Self {
        Self
    }
}

impl<const N: usize> Ideal for XnMinusOneIdeal<N> {}

impl<F: PrimeField, const N: usize> IdealCheck<DynamicPolynomialF<F>>
    for IdealOrZero<XnMinusOneIdeal<N>>
{
    fn contains(&self, value: &DynamicPolynomialF<F>) -> bool {
        if value.is_zero() {
            return true;
        }

        match &self.ideal_or_zero {
            None => value.is_zero(),
            Some(_) => {
                // p ∈ (X^N - 1) iff the coefficient-fold mod X^N - 1 is zero:
                // for each k in 0..N, Σ_{i ≡ k (mod N)} coeffs[i] == 0.
                assert!(N > 0, "XnMinusOneIdeal requires N > 0");
                let cfg = value.coeffs[0].cfg();
                let mut fold: Vec<F> = (0..N).map(|_| F::zero_with_cfg(cfg)).collect();
                for (i, c) in value.coeffs.iter().enumerate() {
                    fold[i % N] += c.clone();
                }
                fold.iter().all(F::is_zero)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crypto_bigint::{Odd, Uint, modular::MontyParams};
    use crypto_primitives::{FromWithConfig, crypto_bigint_monty::MontyField};

    type F = MontyField<4>;

    fn test_cfg() -> MontyParams<4> {
        let modulus = Uint::<4>::from_be_hex(
            "0000000000000000000000000000000000860995AE68FC80E1B1BD1E39D54B33",
        );
        MontyParams::new(Odd::new(modulus).expect("modulus should be odd"))
    }

    fn field(i: i64, cfg: &MontyParams<4>) -> F {
        let mut x = F::from_with_cfg(&u128::from(i.unsigned_abs()), cfg);
        if i < 0 {
            x = -x;
        }
        x
    }

    fn poly(coeffs: &[i64], cfg: &MontyParams<4>) -> DynamicPolynomialF<F> {
        DynamicPolynomialF::new(coeffs.iter().map(|c| field(*c, cfg)).collect::<Vec<_>>())
    }

    #[test]
    fn zero_polynomial_is_in_ideal() {
        let cfg = test_cfg();
        let p = poly(&[0, 0, 0, 0, 0, 0, 0, 0], &cfg);
        let ideal = IdealOrZero::<XnMinusOneIdeal<4>> {
            ideal_or_zero: Some(XnMinusOneIdeal::<4>),
        };
        assert!(ideal.contains(&p));
    }

    #[test]
    fn q_times_x_n_minus_one_is_in_ideal() {
        // p(X) = 5 - 5 X^4 = -5 * (X^4 - 1)
        let cfg = test_cfg();
        let p = poly(&[5, 0, 0, 0, -5], &cfg);
        let ideal = IdealOrZero::<XnMinusOneIdeal<4>> {
            ideal_or_zero: Some(XnMinusOneIdeal::<4>),
        };
        assert!(ideal.contains(&p));
    }

    #[test]
    fn general_multiple_of_x_n_minus_one_is_in_ideal() {
        // Cross-check via explicit folding: every block of length N
        // is the same polynomial with alternating signs — classic way
        // to obtain something in (X^N - 1).
        // p(X) = (1 + 2X + 3X^2 + 4X^3) * (X^4 - 1)
        //      = -(1 + 2X + 3X^2 + 4X^3) + (X^4 + 2X^5 + 3X^6 + 4X^7)
        //      = [-1, -2, -3, -4, 1, 2, 3, 4]
        let cfg = test_cfg();
        let p = poly(&[-1, -2, -3, -4, 1, 2, 3, 4], &cfg);
        let ideal = IdealOrZero::<XnMinusOneIdeal<4>> {
            ideal_or_zero: Some(XnMinusOneIdeal::<4>),
        };
        assert!(ideal.contains(&p));
    }

    #[test]
    fn non_multiple_is_not_in_ideal() {
        // Fold at position 0 is 1, not zero.
        let cfg = test_cfg();
        let p = poly(&[1, 0, 0, 0, 0, 0, 0, 0], &cfg);
        let ideal = IdealOrZero::<XnMinusOneIdeal<4>> {
            ideal_or_zero: Some(XnMinusOneIdeal::<4>),
        };
        assert!(!ideal.contains(&p));
    }

    #[test]
    fn non_multiple_with_nonzero_fold_is_not_in_ideal() {
        // folds: [1+5, 2, 3, 4] = [6, 2, 3, 4], not all zero.
        let cfg = test_cfg();
        let p = poly(&[1, 2, 3, 4, 5], &cfg);
        let ideal = IdealOrZero::<XnMinusOneIdeal<4>> {
            ideal_or_zero: Some(XnMinusOneIdeal::<4>),
        };
        assert!(!ideal.contains(&p));
    }

    #[test]
    fn zero_ideal_only_contains_zero_polynomial() {
        let cfg = test_cfg();
        let zero_ideal = IdealOrZero::<XnMinusOneIdeal<4>>::zero();
        assert!(zero_ideal.contains(&poly(&[0, 0, 0, 0], &cfg)));
        assert!(!zero_ideal.contains(&poly(&[1, 0, 0, 0, -1], &cfg)));
    }
}
