use ark_std::{boxed::Box, marker::PhantomData, vec::Vec};
use crypto_primitives::FromPrimitiveWithConfig;
use prover::{ProverMsg, ProverState};
use thiserror::Error;
use zinc_poly::{mle::DenseMultilinearExtension, utils::ArithErrors};
use zinc_transcript::traits::{ConstTranscribable, Transcript};
use zinc_utils::mul_by_scalar::MulByScalar;

use crate::sumcheck::verifier::VerifierState;

use self::verifier::SubClaim;

pub mod prover;
// pub mod utils;
pub mod verifier;

#[cfg(test)]
mod tests;

/// Interactive Proof for Multilinear Sumcheck
pub struct IPForMLSumcheck<F>(PhantomData<F>);
#[derive(Error, Debug)]
pub enum SumCheckError<F> {
    #[error("univariate polynomial evaluation error")]
    EvaluationError(ArithErrors),
    #[error("incorrect sumcheck sum. Expected `{0}`. Received `{1}`")]
    SumCheckFailed(Box<F>, Box<F>),
    #[error("max degree exceeded")]
    MaxDegreeExceeded,
    #[error("invalid proof length: expected {expected}, got {got}")]
    InvalidProofLength { expected: usize, got: usize },
}

impl<F> From<ArithErrors> for SumCheckError<F> {
    fn from(arith_error: ArithErrors) -> Self {
        Self::EvaluationError(arith_error)
    }
}

/// Sumcheck for products of multilinear polynomial
pub struct MLSumcheck<F>(PhantomData<F>);

/// proof generated by prover
#[derive(Clone, Debug, PartialEq)]
pub struct SumcheckProof<F>(pub Vec<ProverMsg<F>>);

impl<F: FromPrimitiveWithConfig> MLSumcheck<F> {
    /// extract sum from the proof
    pub fn extract_sum(proof: &SumcheckProof<F>) -> F {
        proof.0[0].evaluations[0].clone() + proof.0[0].evaluations[1].clone()
    }

    /// This function does the same thing as `prove`, but it uses cryptographic
    /// sponge as the transcript/to generate the verifier challenges.
    /// Additionally, it returns the prover's state in addition to the proof.
    /// Both of these allow this sumcheck to be better used as a part of a
    /// larger protocol.
    pub fn prove_as_subprotocol(
        transcript: &mut impl Transcript,
        mles: Vec<DenseMultilinearExtension<F>>,
        nvars: usize,
        degree: usize,
        comb_fn: impl Fn(&[F]) -> F + Send + Sync,
        config: F::Config,
    ) -> (SumcheckProof<F>, ProverState<F>)
    where
        F::Inner: ConstTranscribable,
        for<'a> F: MulByScalar<&'a F>,
    {
        let mut buf = vec![0; F::Inner::NUM_BYTES];
        let nvars_field = F::from_with_cfg(nvars as u64, &config);
        let degree_field = F::from_with_cfg(degree as u64, &config);

        transcript.absorb_random_field(&nvars_field, &mut buf);
        transcript.absorb_random_field(&degree_field, &mut buf);
        if nvars == 0 {
            let base_vals: Vec<F> = mles
                .iter()
                .map(|m| {
                    m.evaluate(&[], F::zero_with_cfg(&config))
                        .expect("eval at empty point")
                })
                .collect();
            let _sum_at_empty = comb_fn(&base_vals);

            let prover_state = ProverState {
                randomness: Vec::new(),
                mles,
                num_vars: 0,
                max_degree: degree,
                round: 0,
            };
            return (SumcheckProof(Vec::new()), prover_state);
        }
        let mut prover_state = ProverState::new(mles, nvars, degree);
        let mut verifier_msg = None;
        let mut prover_msgs = Vec::with_capacity(nvars);

        for _ in 0..nvars {
            let prover_msg = prover_state.prove_round(&verifier_msg, &comb_fn, &config);
            transcript.absorb_random_field_slice(&prover_msg.evaluations, &mut buf);
            prover_msgs.push(prover_msg);
            let next_verifier_msg = transcript.get_field_challenge(&config);
            transcript.absorb_random_field(&next_verifier_msg, &mut buf);

            verifier_msg = Some(next_verifier_msg);
        }
        if let Some(vmsg) = verifier_msg {
            prover_state.randomness.push(vmsg);
        }

        (SumcheckProof(prover_msgs), prover_state)
    }

    /// This function does the same thing as `prove`, but it uses a
    /// cryptographic sponge as the transcript/to generate the
    /// verifier challenges. This allows this sumcheck to be used as a part of a
    /// larger protocol.
    pub fn verify_as_subprotocol(
        transcript: &mut impl Transcript,
        num_vars: usize,
        degree: usize,
        claimed_sum: F,
        proof: &SumcheckProof<F>,
        config: F::Config,
    ) -> Result<SubClaim<F>, SumCheckError<F>>
    where
        F::Inner: ConstTranscribable,
    {
        let mut buf = vec![0; F::Inner::NUM_BYTES];

        let (nvars_field, degree_field): (F, F) = {
            (
                F::from_with_cfg(num_vars as u64, &config),
                F::from_with_cfg(degree as u64, &config),
            )
        };
        transcript.absorb_random_field(&nvars_field, &mut buf);
        transcript.absorb_random_field(&degree_field, &mut buf);

        if num_vars == 0 {
            transcript.absorb_random_field(&claimed_sum, &mut buf);
            return Ok(SubClaim {
                point: Vec::new(),                // empty point
                expected_evaluation: claimed_sum, // f(∅)
            });
        }

        if proof.0.len() != num_vars {
            return Err(SumCheckError::InvalidProofLength {
                expected: num_vars,
                got: proof.0.len(),
            });
        }

        let mut verifier_state = VerifierState::new(num_vars, degree, &config);

        for i in 0..num_vars {
            let prover_msg = &proof.0[i];
            transcript.absorb_random_field_slice(&prover_msg.evaluations, &mut buf);
            let verifier_msg = verifier_state.verify_round(prover_msg, transcript);
            transcript.absorb_random_field(&verifier_msg, &mut buf);
        }

        verifier_state.check_and_generate_subclaim(claimed_sum, &config)
    }
}
