#!/usr/bin/env python3
from __future__ import annotations

import argparse
import html
import json
import subprocess
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate a rustdoc landing page (index.html) for a Cargo workspace."
    )
    parser.add_argument(
        "--out",
        required=True,
        type=Path,
        help="Output path for index.html (e.g. target/doc/index.html).",
    )
    args = parser.parse_args()

    metadata_raw = subprocess.check_output(
        ["cargo", "metadata", "--no-deps", "--format-version", "1"],
        text=True,
    )
    metadata = json.loads(metadata_raw)

    workspace_members = set(metadata.get("workspace_members", []))
    packages = metadata.get("packages", [])

    workspace_packages = [
        p for p in packages if p.get("id") in workspace_members and p.get("name")
    ]
    crate_names = sorted({p["name"] for p in workspace_packages})

    items: list[str] = []
    for name in crate_names:
        rustdoc_dir = name.replace("-", "_")
        items.append(
            f'<li><a href="./{html.escape(rustdoc_dir)}/">{html.escape(name)}</a></li>'
        )

    out_path: Path = args.out
    out_path.parent.mkdir(parents=True, exist_ok=True)

    page = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Zinc+ Rust Docs</title>
    <style>
      :root { color-scheme: light dark; }
      body {
        font-family: system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
        margin: 0;
        padding: 2rem 1.25rem;
        line-height: 1.5;
      }
      main { max-width: 56rem; margin: 0 auto; }
      h1 { margin: 0 0 0.5rem 0; font-size: 2rem; }
      p { margin: 0.25rem 0 1.25rem 0; opacity: 0.9; }
      ul { padding-left: 1.25rem; margin: 0; }
      li { margin: 0.35rem 0; }
      code {
        font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
      }
    </style>
  </head>
  <body>
    <main>
      <h1>Zinc+ Rust Docs</h1>
      <p>Workspace crate documentation generated by <code>cargo doc</code>.</p>
      <p><a href="https://github.com/NethermindEth/zinc-plus">Repository README</a></p>
      <ul>
        __ITEMS__
      </ul>
    </main>
  </body>
</html>
"""
    out_path.write_text(page.replace("__ITEMS__", "\n        ".join(items)), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
