name: Build and test code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Give GitHub Actions access to crypto-primitives
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/checkout@v4
      - name: Build
        run: cargo test --workspace --verbose --no-run
      - name: Run tests
        run: cargo test --workspace --verbose
