name: UB (undefined behavior) detection

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  ub-detection:
    if: github.event.pull_request.draft == false
    name: Check for undefined behaviour (UB)
    timeout-minutes: 480
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          rustup +nightly component add miri
          cargo +nightly miri setup
          MIRIFLAGS="-Zmiri-env-forward=PROPTEST_DISABLE_FAILURE_PERSISTENCE -Zmiri-strict-provenance -Zmiri-disable-isolation" \
            cargo +nightly miri test --lib
